export const TYPES = {
  ApiKey: Symbol('ApiKey'),
  ArchiveArchivist: Symbol('ArchiveArchivist'),
  ArchiveArchivistMongoDb: Symbol('ArchiveArchivistMongoDb'),
  ArchivePermissionsArchivist: Symbol('ArchivePermissionsArchivist'),
  ArchiveSdkMongo: Symbol('ArchiveSdkMongo'),
  Logger: Symbol('Logger'),
  PasswordHasher: Symbol('PasswordHasher'),
  QueryQueue: Symbol('QueryQueue'),
  ResponseQueue: Symbol('ResponseQueue'),
  SchemaToQueryProcessorRegistry: Symbol('SchemaToQueryProcessorRegistry'),
  UserArchivist: Symbol('UserArchivist'),
  UserArchivistMongoDb: Symbol('UserArchivistMongoDb'),
  UserManager: Symbol('UserManager'),
  UserManagerMongoDb: Symbol('UserManagerMongoDb'),
  UserSdkMongo: Symbol('UserSdkMongo'),
  WitnessedPayloadArchivist: Symbol('WitnessedPayloadArchivist'),
  XyoAccount: Symbol('XyoAccount'),
  XyoPayloadToQueryConverterRegistry: Symbol('XyoPayloadToQueryConverterRegistry'),
}
