export const TYPES = {
  Account: Symbol('Account'),
  ApiKey: Symbol('ApiKey'),
  ArchiveArchivist: Symbol('ArchiveArchivist'),
  ArchiveKeyArchivist: Symbol('ArchiveKeyArchivist'),
  ArchivePermissionsArchivist: Symbol('ArchivePermissionsArchivist'),
  JwtSecret: Symbol('JwtSecret'),
  Logger: Symbol('Logger'),
  PasswordHasher: Symbol('PasswordHasher'),
  PayloadToQueryConverterRegistry: Symbol('PayloadToQueryConverterRegistry'),
  QueryQueue: Symbol('QueryQueue'),
  ResponseQueue: Symbol('ResponseQueue'),
  SchemaCountDiviner: Symbol('SchemaCountDiviner'),
  SchemaToQueryProcessorRegistry: Symbol('SchemaToQueryProcessorRegistry'),
  UserArchivist: Symbol('UserArchivist'),
  UserManager: Symbol('UserManager'),
  WitnessedPayloadArchivist: Symbol('WitnessedPayloadArchivist'),
}
