export const TYPES = {
  Account: Symbol('Account'),
  ApiKey: Symbol('ApiKey'),
  ArchiveArchivist: Symbol('ArchiveArchivist'),
  ArchiveBoundWitnessesArchivist: Symbol('ArchiveBoundWitnessesArchivist'),
  ArchiveKeyArchivist: Symbol('ArchiveKeyArchivist'),
  ArchivePayloadsArchivist: Symbol('ArchivePayloadsArchivist'),
  ArchivePermissionsArchivist: Symbol('ArchivePermissionsArchivist'),
  ArchiveSchemaCountDiviner: Symbol('ArchiveSchemaCountDiviner'),
  ArchiveSchemaListDiviner: Symbol('ArchiveSchemaListDiviner'),
  BoundWitnessStatsDiviner: Symbol('BoundWitnessStatsDiviner'),
  BoundWitnessesArchivist: Symbol('BoundWitnessesArchivist'),
  JobQueue: Symbol('JobQueue'),
  JwtSecret: Symbol('JwtSecret'),
  Logger: Symbol('Logger'),
  PasswordHasher: Symbol('PasswordHasher'),
  PayloadStatsDiviner: Symbol('PayloadStatsDiviner'),
  PayloadToQueryConverterRegistry: Symbol('PayloadToQueryConverterRegistry'),
  PayloadsArchivist: Symbol('PayloadsArchivist'),
  QueryQueue: Symbol('QueryQueue'),
  ResponseQueue: Symbol('ResponseQueue'),
  SchemaToQueryProcessorRegistry: Symbol('SchemaToQueryProcessorRegistry'),
  UserArchivist: Symbol('UserArchivist'),
  UserManager: Symbol('UserManager'),
  WitnessedPayloadArchivist: Symbol('WitnessedPayloadArchivist'),
}
